---
- name: "Install Prerequisites."
  ansible.builtin.package:
    name: apt-transport-https
    state: present
  when: repos_transport_protocol == "https"

- name: "Update the Configuration Files."
  become: true
  ansible.builtin.template:
    src: Debian.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    owner: root
    group: root
    backup: true
  when: not repos_custom_repository_urls | length

- name: "Define Custom sources.list Configuration."
  become: true
  ansible.builtin.template:
    src: custom.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    owner: root
    group: root
    backup: true
  when: repos_custom_repository_urls | length

- name: "Define additional sources.d Configuration."
  become: true
  ansible.builtin.template:
    src: additional.list.j2
    dest: "/etc/apt/sources.list.d/{{ item.name }}"
    mode: 0644
    owner: root
    group: root
    backup: true
  when: repos_additional_repository_urls | length
  loop: "{{ repos_additional_repository_urls }}"

- name: "Verify Changes."
  ansible.builtin.command: apt-get update  # noqa command-instead-of-module
  register: apt_output
  changed_when: apt_output.rc == "100"
  ignore_errors: true
