---
- name: "Update the Configuration Files."
  become: 'yes'
  template:
    src: "{{ item }}.j2"
    dest: "/etc/yum.repos.d/{{ item }}"
    mode: 0644
    owner: root
    group: root
    setype: system_conf_t
    backup: 'yes'
  with_items:
    - fedora.repo
    - fedora-updates.repo
    - fedora-updates-testing.repo
    - fedora-updates-testing-modular.repo
    - fedora-updates-modular.repo
    - fedora-modular.repo
    - fedora-cisco-openh264.repo

- name: "Verify Changes."
  shell: dnf check-update --refresh
  args:
    executable: /bin/bash
    warn: 'false'
  register: dnf_output
  changed_when: dnf_output.rc == "100"
  failed_when: dnf_output.rc == "3" or dnf_output.rc == "200"
