---
- name: Preflight - Fail if target host is not stable for this Role.
  fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in repos_stable_os)

- name: "Include Distribution specific Variables."
  include_vars: "{{ ansible_distribution }}.yml"
  changed_when: 'false'
  failed_when: 'false'

- name: Include Distribution specific Playbook.
  include_tasks: "{{ ansible_distribution }}.yml"
